### YamlMime:ManagedReference
items:
- uid: Others.ApplicationRuntimeManager
  commentId: T:Others.ApplicationRuntimeManager
  id: ApplicationRuntimeManager
  parent: Others
  children:
  - Others.ApplicationRuntimeManager.QuitApplication
  - Others.ApplicationRuntimeManager.StartTraining(System.Int32)
  langs:
  - csharp
  - vb
  name: ApplicationRuntimeManager
  nameWithType: ApplicationRuntimeManager
  fullName: Others.ApplicationRuntimeManager
  type: Class
  source:
    id: ApplicationRuntimeManager
    path: ''
    startLine: 3382
  assemblies:
  - cs.temp.dll
  namespace: Others
  syntax:
    content: 'public class ApplicationRuntimeManager : MonoBehaviour'
    content.vb: >-
      Public Class ApplicationRuntimeManager
          Inherits MonoBehaviour
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Others.ApplicationRuntimeManager.QuitApplication
  commentId: M:Others.ApplicationRuntimeManager.QuitApplication
  id: QuitApplication
  parent: Others.ApplicationRuntimeManager
  langs:
  - csharp
  - vb
  name: QuitApplication()
  nameWithType: ApplicationRuntimeManager.QuitApplication()
  fullName: Others.ApplicationRuntimeManager.QuitApplication()
  type: Method
  source:
    id: QuitApplication
    path: ''
    startLine: 3389
  assemblies:
  - cs.temp.dll
  namespace: Others
  summary: "\nQuits the whole Application\n\nWhen in Editor, just stops the preview\n"
  example: []
  syntax:
    content: public void QuitApplication()
    content.vb: Public Sub QuitApplication
  overload: Others.ApplicationRuntimeManager.QuitApplication*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Others.ApplicationRuntimeManager.StartTraining(System.Int32)
  commentId: M:Others.ApplicationRuntimeManager.StartTraining(System.Int32)
  id: StartTraining(System.Int32)
  parent: Others.ApplicationRuntimeManager
  langs:
  - csharp
  - vb
  name: StartTraining(Int32)
  nameWithType: ApplicationRuntimeManager.StartTraining(Int32)
  fullName: Others.ApplicationRuntimeManager.StartTraining(System.Int32)
  type: Method
  source:
    id: StartTraining
    path: ''
    startLine: 3402
  assemblies:
  - cs.temp.dll
  namespace: Others
  summary: "\nStarts a Training with the provided ID\n"
  example: []
  syntax:
    content: public void StartTraining(int trainingID)
    parameters:
    - id: trainingID
      type: System.Int32
      description: ''
    content.vb: Public Sub StartTraining(trainingID As Integer)
  overload: Others.ApplicationRuntimeManager.StartTraining*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Others
  commentId: N:Others
  name: Others
  nameWithType: Others
  fullName: Others
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Others.ApplicationRuntimeManager.QuitApplication*
  commentId: Overload:Others.ApplicationRuntimeManager.QuitApplication
  name: QuitApplication
  nameWithType: ApplicationRuntimeManager.QuitApplication
  fullName: Others.ApplicationRuntimeManager.QuitApplication
- uid: Others.ApplicationRuntimeManager.StartTraining*
  commentId: Overload:Others.ApplicationRuntimeManager.StartTraining
  name: StartTraining
  nameWithType: ApplicationRuntimeManager.StartTraining
  fullName: Others.ApplicationRuntimeManager.StartTraining
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
